# version: '3'
# services: 
#     web: 
#         build: .
#         ports: 
#             - "8080:8080"

        
#     db: 
#         image: "mysql"
#         environment: 
#             MYSQL_ROOT_PASSWORD: edaedaeda

#         volume:
#             - db-data:/foo

# volumes: 
#     db-data:
        
        
# # running this file
# #docker-compose up

# # shuting down all docker containers
# #docker-compose down


version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

    #   kafka can't run without zookeper
    # to start run docker-compose up

    #to create the topic
      
    # docker exec kafka kafka-topics.sh --create --zookeeper zookeeper:2181  --replication-factor 1  --partitions 1 --topic yombi-topic-test-2

